# Generated by Django 5.2.4 on 2025-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('FICÇÃO CIENTÍFICA', 'Ficção Científica'), ('FANTASIA', 'Fantasia'), ('BIOGRAFIA', 'Biografia'), ('NEGÓCIOS E ECONÔMIA', 'Negôcios e Econômia'), ('CIÊNCIAS', 'Ciências'), ('OUTROS', 'Outros')], default='', max_length=100),
        ),
    ]
