# Generated by Django 5.2.4 on 2025-07-26 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_publicada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
