# Generated by Django 5.2.4 on 2025-07-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_data_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
