# Generated by Django 5.2.4 on 2025-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
