# Generated by Django 5.2.4 on 2025-08-06 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('FICÇÃO CIENTÍFICA', 'Ficção Científica'), ('FANTASIA', 'Fantasia'), ('BIOGRAFIA', 'Biografia'), ('NEGÓCIOS E ECONÔMIA', 'Negócios e Econômia'), ('CIÊNCIAS', 'Ciências'), ('OUTROS', 'Outros')], default='', max_length=100),
        ),
    ]
