# Generated by Django 5.2.4 on 2025-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livro_usuario_alter_livro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('FICÇÃO CIENTÍFICA', 'Ficção Científica'), ('FANTASIA', 'Fantasia'), ('BIOGRAFIA', 'Biografia'), ('NEGÓCIOS E ECONÔMIA', 'Negócios e Econômia'), ('CIÊNCIAS', 'Ciências'), ('AVENTURA', 'Aventura'), ('OUTROS', 'Outros')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
